site_name: Fink
repo_url: https://github.com/astrolabsoftware/fink-broker
edit_uri: ""

nav:
    - Home: index.md
    - Broker:
      - Sience in Fink: science/introduction.md
      - Technological consideration: broker/introduction.md
      - Fink alert added values: science/added_values.md
      - Available Fink topics: topics.md
      - Tutorials: tutorials/introduction.md
    - Client:
      - Connect to Fink streams: topics.md
      - Tutorial: https://github.com/astrolabsoftware/fink-tutorials
    - About:
      - Who is behind Fink?: who-is-fink.md
      - Release Notes: release-notes.md
      - Contributing: contributing.md
    - Connect &#9889;: https://forms.gle/2td4jysT4e9pkf889

theme:
  name: readthedocs
  collapse_navigation: True
  titles_only: True
  navigation_depth: 0
# theme:
#     name: mkdocs
#     nav_style: dark

copyright: Copyright &copy; 2018-20 <a href="https://astrolabsoftware.github.io/">AstroLab Software</a>.
