site_name: Fink
repo_url: https://github.com/astrolabsoftware/fink-broker
edit_uri: ""

nav:
    - Home: index.md
    - Broker:
      - Science Roadmap: broker/roadmap.md
      - Technological consideration: broker/introduction.md
      - Fink science modules: broker/science_modules.md
      - Fink filters: broker/filters.md
      - Alert Classification: broker/classification.md
    - Services:
      - Summary: services/summary.md
      - Livestream: services/livestream.md
      - Science Portal and API: services/science_portal.md
      - Data Transfer: services/data_transfer.md
    - About:
      - Source code: source-code.md
      - Release Notes: release-notes.md
      - Contributing: contributing.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - admonition

copyright: Copyright &copy; 2018-24 <a href="https://fink-broker.org">Fink team</a>.
