site_name: Fink
repo_url: https://github.com/astrolabsoftware/fink-broker
edit_uri: ""

nav:
    - Home: index.md
    - Technology:
      - Getting started: broker/introduction.md
      - Broker commands: broker/cheatsheet.md
      # - Configuration: broker/configuration.md
      # - Databases: broker/database.md
      # - Services: broker/available-services.md
      # - Dashboard: broker/dashboard.md
      - Simulating streams: broker/simulator.md
      - Testing Fink broker: broker/testing-fink.md
      - Redistributing alerts using Kafka: broker/streaming-out.md
      # - Howto: broker/howto.md
    - Science: science/introduction.md
    - Distribution: distribution/introduction.md
    - Tutorials:
      - Deploy the broker (local & cloud): toto.md
      - Create your Science module: toto.md
      - Create your Fink filter: toto.md
      - Collect Fink alerts: toto.md
    # - Tutorials:
    #   - Collecting alerts: tutorials/raw_db.md
    #   - Applying quality cuts: tutorials/bogus_filtering.md
    #   - Processing alerts: tutorials/processing_alerts.md
    #   - Redistributing alerts: tutorials/redistributing_alerts.md
    #   - Kafka Security: tutorials/secured_kafka.md
    - About:
      - Why Fink: why-fink.md
      - Who we are: fink-team.md
      - Release Notes: release-notes.md
      - Contributing: contributing.md
      - License: license.md
    # - Cheatsheet: cheatsheet.md

# theme: readthedocs

copyright: Copyright &copy; 2018-19 <a href="https://astrolabsoftware.github.io/">AstroLab Software</a>.
